version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=30000
      - PGID=30000
    volumes:
      - /daten/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
